= Zoltyj Mastodon Client =

== What's this? ==
This is an experimental Mastodon client for just reading ("nagashiyomi") and tooting.

License: the Apache License, Version 2.0
( Copyright hiromi-mi 2019, See `LICENSE`)

== Dependency ==

These dependency are not installed automatically.
* mastodon-api : MIT License
* nokogiri : MIT License
* ruby-gpgme (to save access token with encryption) : LGPL-2.1
  Its dependencies are shown below: https://nokogiri.org/LICENSE-DEPENDENCIES.html
* GnuPG 

You can install by using `bundle update --vendor bundle/vendor` or `gem install`.

=== How to Use ===

=== Initial Setup ===
Add `config.yaml` *with permission 700* into your installed directory, and write as follows:

.Example config.yaml
----
baseurl: https://(your base domain)
----

Append `baseurl` into `config.yaml`, run `ruby auth.rb` and follow its procedure.

=== Watch Your Home Timeline ===
Just type `ruby main.rb`. 
You can watch your home timeline per every 30 seconds.

=== Compose Toot ===
Type `ruby main.rb (Reply ID if any)` and compose toot into input procedure. After typing, press enter.

Newline can be written as CTRL-M.

That's all.
